package com.clinica.modelo;
// Generated 7/12/2013 11:46:38 AM by Hibernate Tools 3.6.0

import java.util.Date;


/**
 * Egreso generated by hbm2java
 */
public class Egreso implements java.io.Serializable {

    public Egreso() {
    }

    public Egreso(String concepto, String tipoEgreso, String proveedor) {
        this.concepto = concepto;
        this.tipoEgreso = tipoEgreso;
        this.proveedor = proveedor;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getConcepto() {
        return this.concepto;
    }

    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }

    public String getTipoEgreso() {
        return this.tipoEgreso;
    }

    public void setTipoEgreso(String tipoEgreso) {
        this.tipoEgreso = tipoEgreso;
    }

    public String getProveedor() {
        return this.proveedor;
    }

    public void setProveedor(String proveedor) {
        this.proveedor = proveedor;
    }

    public double getMonto() {
        return monto;
    }

    public void setMonto(double monto) {
        this.monto = monto;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    

    /*
    Atributos privados
    */
    private int id;
    private String concepto;
    private String tipoEgreso;
    private String proveedor;
    private double monto;
    private Date fecha;

}
