package com.clinica.modelo;
// Generated 7/12/2013 11:46:38 AM by Hibernate Tools 3.6.0

import java.util.Date;


/**
 * Ingreso generated by hbm2java
 */
public class Ingreso implements java.io.Serializable {

    public Ingreso() {
    }

    public Ingreso(String concepto, String tipoDeIngreso) {
        this.concepto = concepto;
        this.tipoDeIngreso = tipoDeIngreso;

    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getConcepto() {
        return this.concepto;
    }

    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }

    public String getTipoDeIngreso() {
        return this.tipoDeIngreso;
    }

    public void setTipoDeIngreso(String tipoDeIngreso) {
        this.tipoDeIngreso = tipoDeIngreso;
    }

    public String getMonto() {
        return this.monto;
    }

    public void setMonto(String monto) {
        this.monto = monto;
    }

    public Date getFechaDeVenta() {
        return fechaDeVenta;
    }

    public void setFechaDeVenta(Date fechaDeVenta) {
        this.fechaDeVenta = fechaDeVenta;
    }
    
    /*
     Atributos privados clase ingreso
     */
    private Integer id;
    private String concepto;
    private Date fechaDeVenta;
    private String monto;
    private String tipoDeIngreso;
    

}
