package com.clinica.modelo;
// Generated 7/12/2013 11:46:38 AM by Hibernate Tools 3.6.0

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor implements java.io.Serializable {

    public Proveedor() {
    }

    public Proveedor(String nombre, String direccion, String telefono, String rfc) {
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
        this.rfc = rfc;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getRfc() {
        return this.rfc;
    }

    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    
    
    public String getEmail() {
        return email;
    }

 
    public String getFax() {
        return fax;
    }

    /*
    Atributos privados clase Proveedor
    */
    private Integer id;
    private String nombre;
    private String direccion;
    private String telefono;
    private String rfc;
    private String email;
    private String fax;

    

}
