package com.clinica.modelo;
// Generated 3/11/2013 08:23:07 PM by Hibernate Tools 3.2.1.GA



/**
 * Usuarios generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {

    public Usuario() {
    }

    public Usuario(String nombre, String contrasena, String administrador) {
       this.nombre = nombre;
       this.contrasena = contrasena;
       this.administrador = administrador;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(String administrador) {
        this.administrador = administrador;
    }
    
    /*
    Atributos privados
    */
     private Integer id;
     private String nombre;
     private String contrasena;
     private String administrador;


}


